### ISSUE TITLE
Make configs configurable and optional

### ISSUE THREAD

**Issue by vjik** [yiisoft/yii-runner-console#7]
1) Add ability change configuration group names for definitions, providers and delegates.

2) By default names can be `null` and don't load.

**Comment by devanych** [comment]
> 1. Add ability change configuration group names for definitions, providers and delegates.
> 
> 2. By default names can be `null` and don't load.

There is a `withConfig()` method for this, where you can configure anything you want.

https://github.com/yiisoft/yii-runner-console/blob/master/src/ConsoleApplicationRunner.php#L82

**Comment by vjik** [comment]
Oh, yes.

**Comment by terabytesoftw** [comment]
> > 1. Add ability change configuration group names for definitions, providers and delegates.
> > 2. By default names can be `null` and don't load.
> 
> There is a `withConfig()` and `withContainer()` methods for this, where you can configure anything you want.

It is correct but I think that we should make the configuration even easier, for example if I only want to change a part because I have to write the whole configuration example: 

https://github.com/yii-extension/simple-app/blob/master/public/index.php#L45

If I only want to add or delete groups because I have to write all the configuration, I particularly have no problem, but we can make it easier.

**Comment by vjik** [comment]
We can check existing of `providers-console` and `delegates-console` config groups.
